// @ts-check
import { defineConfig } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
import icon from "astro-icon";
import sitemap from "@astrojs/sitemap";

// https://astro.build/config
export default defineConfig({
  site: "https://vincentiwadsworth.github.io",
  base: "/cbhe-web",
  integrations: [
    sitemap({
      filter: (page) => !page.includes("/gracias") && !page.includes("/verificar"),
    }),
    icon({
      include: {
        "material-symbols": [
          "bolt",
          "search",
          "arrow-back",
          "arrow-forward",
          "explore",
          "engineering",
          "factory",
          "local-shipping",
          "handyman",
          "check-circle",
          "send",
          "flag",
          "visibility",
          "landscape",
          "precision-manufacturing",
          "route",
          "support-agent",
          "school",
          "arrow-downward",
          "calendar-today",
          "schedule",
          "desktop-windows",
          "apartment",
          "devices",
          "refresh",
          "verified",
          "security",
          "account-balance",
          "science",
          "language",
          "architecture",
          "category",
          "history",
          "expand-more",
          "menu",
          "close",
          "location-on",
          "call",
          "mail",
          "map",
          "open-in-new",
          "chat",
          "description",
          "gavel",
          "fact-check",
          "groups",
          "payments",
          "task-alt",
          "oil-barrel",
          "local-fire-department",
          "euro",
          "currency-exchange",
          "qr-code-2",
          "palette",
          "light-mode",
          "dark-mode",
          "format-quote",
          "person",
          "sort-by-alpha",
        ],
      },
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
});
